# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
apt_packages:
  - libudunits2-dev
  - libgdal-dev
r_binary_packages:
  - sf
after_success:
  - Rscript -e 'covr::codecov()'
